[package]
name = "spectre"
version = "0.1.0"
authors = ["Will Hart <hart.wl@gmail.com>"]
edition = "2018"
exclude = ["assets/**/*", "crates/**/*"]

[workspace]
members = [
  "crates/*"
]

[profile.dev]
opt-level = 3

[profile.release]
lto = true
opt-level = 3
incremental = false
codegen-units = 1

[patch.crates-io]
# Can revert to default branch when PR 580 is merged
bevy = { git = "https://github.com/bevyengine/bevy"  }

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
serde = { version = "1", features = ["derive"]}

# Local dependencies
spectre_animations = { path = "crates/spectre_animations", version = "0.1" }
spectre_combat = { path = "crates/spectre_combat", version = "0.1" }
spectre_core = { path = "crates/spectre_core", version="0.1" }
spectre_loaders = { path = "crates/spectre_loaders", version="0.1" }
spectre_state = { path = "crates/spectre_state", version="0.1" }
spectre_time = { path = "crates/spectre_time", version="0.1" }

